version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # Persist models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"  # n8n default port
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true  # Enable auth (optional)
      - N8N_BASIC_AUTH_USER=${N8N_USER}     # Replace with your credentials
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PSSWD}
    volumes:
      - n8n_data:/home/node/.n8n  # Persist workflows
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
  n8n_data:
